version: '3.5'
volumes:
    prometheus_data: {}
    grafana_data: {}
services:
  restapi:
    build: ./restapi
    ports:
      - "5000:5000"
    networks:
      - backend

  webapp:
    build: ./webapp
    ports:
      - "3000:3000"
    depends_on: 
      - restapi
  prometheus:
    image: prom/prometheus
    volumes:
      - ./restapi/monitoring/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    depends_on: 
      - restapi
  grafana:
    image: grafana/grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./restapi/monitoring/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SERVER_HTTP_PORT=9091
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - "9091:9091"
    depends_on: 
      - restapi

  mongo:
    image: mongo
    container_name: mongodb
    hostname: mongodb
    restart: always
    networks:
      - backend
      - mongo-network

  mongo-express: 
    depends_on:
      - mongo
    image: mongo-express:latest 
    hostname: mongo-express 
    environment: 
      ME_CONFIG_MONGODB_SERVER: mongodb
    ports:
      - 8081:8081
    networks:
      - mongo-network
  
networks:
  backend:
    driver: bridge
  mongo-network:
    driver: bridge