version: '3.5'
volumes:
    prometheus_data: {}
    grafana_data: {}
services:
  restapi:
    build: ./restapi
    ports:
      - "5000:5000"
    networks:
      backend:
        ipv4_address: 192.168.1.5

  webapp:
    build: ./webapp
    ports:
      - "3000:3000"
    depends_on: 
      - restapi
  prometheus:
    image: prom/prometheus
    volumes:
      - ./restapi/monitoring/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    depends_on: 
      - restapi
  grafana:
    image: grafana/grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./restapi/monitoring/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SERVER_HTTP_PORT=9091
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - "9091:9091"
    depends_on: 
      - restapi

  mongo:
    image: mongo
    container_name: mongodb
    hostname: mongodb
    restart: always
    ports:
      - "27017:27017"
    expose:
      - 27017
    networks:
      backend:
        ipv4_address: 192.168.1.10

networks:
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24