name: CI for LOMAP_ES6c

on:
  release:
    types: [published]
  pull_request:
    branches: [master, develop]

jobs:

  docker-push-webapp:
    name: Push webapp Docker Image to GitHub Packages
    runs-on: ubuntu-latest
    needs: [e2e-tests]
    steps:
      - uses: actions/checkout@v3
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: arquisoft/lomap_es6c/webapp
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PUSH_TOKEN }} 
          registry: ghcr.io
          workdir: webapp

  deploy:
    name: Deploy over SSH
    runs-on: ubuntu-latest
    needs: [docker-push-webapp] 
    steps:
      - name: Deploy over SSH
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          user: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }} 
          command: |
            wget https://raw.githubusercontent.com/arquisoft/lomap_es6c/master/docker-compose-deploy.yml -O docker-compose.yml
            docker-compose stop
            docker-compose rm -f
            docker-compose pull
            docker-compose up -d
